### ISSUE TITLE
Tracking issue for better unicode support.

### ISSUE THREAD

**Issue by Erk-** [zeyla/is-rust#7]
This is a tracking issue for [RFC#0000](https://gist.github.com/Erk-/3710d92378f86905d859155940b254df).
This RFC upgrades the unicode support of `is_rust`

Steps:
- [ ] Discuss and make Changes to the RFC
- [ ] Ask ourselves if we should do it
- [ ] Write new tests
- [ ] Implement the RFC
- [ ] Adjust documentation
- [ ] Stabilization PR

Unresolved questions:
- Should we do it?
- Do we have to many letter like symbols?
- Should we add more R-like codepoints?

**Comment by zeyla** [comment]
A quick concern before I think about this for a couple minutes and forget about it forever:

Under the "Rationale and alternatives" section you list the rationale as "Don't do it." But in the "Unresolved questions" section, it asks "Should we do it?"

Is the rationale correct? Is it an unresolved question?

**Comment by Erk-** [comment]
Yes

**Comment by Erk-** [comment]
I updated the RFC to be more clear about it.

**Comment by AregevDev** [comment]
It would be a nice addition 👍
